# Generated by ChatGPT

import pytest
from bson import ObjectId
from flaskr.services.mongodb.base_mongodb_service import BaseMongoDBService

@pytest.fixture
def mock_db():
    import mongomock
    client = mongomock.MongoClient()
    return client["test_db"]

@pytest.fixture
def service(mock_db):
    def db_provider():
        return mock_db
    return BaseMongoDBService(db_provider, "test_collection")

def test_get_document_by_id_returns_document(service, mock_db):
    inserted_id = mock_db["test_collection"].insert_one({"name": "Alice"}).inserted_id
    doc = service.get_document_by_id(str(inserted_id))
    assert doc is not None
    assert doc["_id"] == str(inserted_id)
    assert doc["name"] == "Alice"

def test_get_all_documents_returns_list(service, mock_db):
    mock_db["test_collection"].insert_many([{"name": "A"}, {"name": "B"}])
    docs = service.get_all_documents()
    assert len(docs) == 2

def test_get_all_documents_with_filter(service, mock_db):
    mock_db["test_collection"].insert_many([
        {"name": "A", "status": "active"},
        {"name": "B", "status": "inactive"}
    ])
    active_docs = service.get_all_documents({"status": "active"})
    assert len(active_docs) == 1
    assert active_docs[0]["name"] == "A"

def test_update_document_updates_fields(service, mock_db):
    inserted_id = mock_db["test_collection"].insert_one({"name": "Bob"}).inserted_id
    modified = service.update_document(str(inserted_id), {"name": "Robert"})
    assert modified == 1
    doc = mock_db["test_collection"].find_one({"_id": inserted_id})
    assert doc["name"] == "Robert"

def test_delete_document_removes_doc(service, mock_db):
    inserted_id = mock_db["test_collection"].insert_one({"name": "ToDelete"}).inserted_id
    deleted = service.delete_document(str(inserted_id))
    assert deleted == 1
    assert mock_db["test_collection"].find_one({"_id": inserted_id}) is None

def test_delete_all_documents_clears_collection(service, mock_db):
    mock_db["test_collection"].insert_many([{"a": 1}, {"a": 2}])
    deleted_count = service.delete_all_documents()
    assert deleted_count == 2
    assert mock_db["test_collection"].count_documents({}) == 0

def test_get_collection_stats_returns_expected_fields(service, mock_db):
    mock_db["test_collection"].insert_many([
        {"type": "alpha"}, {"type": "beta"}, {"type": "alpha"}
    ])
    stats = service.get_collection_stats()
    assert stats["total_documents"] == 3
    assert stats["type_breakdown"]["alpha"] == 2
    assert stats["type_breakdown"]["beta"] == 1

def test_query_documents_filters_correctly(service, mock_db):
    mock_db["test_collection"].insert_many([
        {"name": "Tom", "status": "active"},
        {"name": "Jane", "status": "inactive"}
    ])
    docs = service.query_documents({"status": "active"})
    assert len(docs) == 1
    assert docs[0]["name"] == "Tom"
