# Generated by ChatGPT

import pytest
from unittest.mock import patch, MagicMock
from datetime import datetime

from flaskr.services.util import report

def test_generate_cred_compliance_report_builds_correct_structure(monkeypatch):
    """Test that generate_cred_compliance_report builds the expected report dict."""

    # Arrange: mock AWSClientManager and its method
    mock_aws_client = MagicMock()
    mock_aws_client.get_users_with_direct_policies.return_value = ["user1", "user2"]

    monkeypatch.setattr("flaskr.services.util.report.AWSClientManager", lambda: mock_aws_client)

    # Act
    result = report.generate_cred_compliance_report()

    # Assert
    assert result["report_type"] == report.ReportType.CRED_COMPLIANCE.value
    assert "report_date_time" in result
    assert isinstance(datetime.fromisoformat(result["report_date_time"]), datetime)
    assert result["uncompliant_users"] == ["user1", "user2"]

    mock_aws_client.get_users_with_direct_policies.assert_called_once()

def test_check_report_type_returns_true_for_matching_type():
    r = {"report_type": report.ReportType.CRED_COMPLIANCE.value}
    assert report.check_report_type(r, report.ReportType.CRED_COMPLIANCE) is True

def test_check_report_type_returns_false_for_non_matching_type():
    r = {"report_type": "something_else"}
    assert report.check_report_type(r, report.ReportType.CRED_COMPLIANCE) is False

def test_check_report_type_handles_missing_key():
    r = {}
    assert report.check_report_type(r, report.ReportType.CRED_COMPLIANCE) is False
