# Generated by ChatGPT

import pytest
from unittest.mock import patch, MagicMock
from flaskr.services.util.mail import BrevoMailer


@pytest.fixture
def mock_app():
    """Fixture that simulates a Flask app with configuration."""
    app = MagicMock()
    app.config = {"BREVO_API_KEY": "fake-api-key"}
    return app


@pytest.fixture
def mailer():
    """Fixture for BrevoMailer instance."""
    return BrevoMailer()


@patch("flaskr.services.util.mail.sib_api_v3_sdk.TransactionalEmailsApi")
@patch("flaskr.services.util.mail.ApiClient")
@patch("flaskr.services.util.mail.Configuration")
def test_init_app(mock_config_cls, mock_api_client_cls, mock_transac_api_cls, mailer, mock_app):
    """Test that init_app sets up the API instance correctly."""
    mock_config = MagicMock()
    mock_config.api_key = {}
    mock_config_cls.return_value = mock_config

    mock_api_client = MagicMock()
    mock_api_client_cls.return_value = mock_api_client

    mock_transac_api = MagicMock()
    mock_transac_api_cls.return_value = mock_transac_api

    mailer.init_app(mock_app)

    # Assert Configuration and ApiClient initialized correctly
    mock_config_cls.assert_called_once()
    assert mock_config.api_key['api-key'] == "fake-api-key"
    mock_api_client_cls.assert_called_once_with(mock_config)
    mock_transac_api_cls.assert_called_once_with(mock_api_client)
    assert mailer.api_instance == mock_transac_api


@patch("flaskr.services.util.mail.os.getenv", return_value="sender@example.com")
@patch("flaskr.services.util.mail.sib_api_v3_sdk.SendSmtpEmail")
def test_send_email_basic(mock_send_email_cls, mock_getenv, mailer):
    """Test sending an email without attachments."""
    mailer.api_instance = MagicMock()

    # Mock SendSmtpEmail instance
    mock_send_email = MagicMock()
    mock_send_email_cls.return_value = mock_send_email

    recipients = ["test@example.com"]
    subject = "Hello"
    html = "<h1>Test</h1>"

    mailer.send_email(subject, recipients, html)

    # Verify sender email pulled from env
    mock_getenv.assert_called_once_with('BREVO_EMAIL')

    # Verify SendSmtpEmail called correctly
    mock_send_email_cls.assert_called_once_with(
        to=[{"email": "test@example.com"}],
        sender={"email": "sender@example.com"},
        subject=subject,
        html_content=html
    )

    # Verify API call executed
    mailer.api_instance.send_transac_email.assert_called_once_with(mock_send_email)


@patch("flaskr.services.util.mail.os.getenv", return_value="sender@example.com")
@patch("flaskr.services.util.mail.sib_api_v3_sdk.SendSmtpEmailAttachment")
@patch("flaskr.services.util.mail.sib_api_v3_sdk.SendSmtpEmail")
def test_send_email_with_attachment(mock_send_email_cls, mock_attach_cls, mock_getenv, mailer):
    """Test sending an email with an attachment."""
    mailer.api_instance = MagicMock()

    mock_send_email = MagicMock()
    mock_send_email_cls.return_value = mock_send_email

    mock_attachment = MagicMock()
    mock_attach_cls.return_value = mock_attachment

    attachment = {"name": "file.txt", "content": "dGVzdCBjb250ZW50"}  # base64 example
    recipients = ["test@example.com"]
    subject = "With Attachment"
    html = "<p>Attached</p>"

    mailer.send_email(subject, recipients, html, attachment)

    # Verify attachment created correctly
    mock_attach_cls.assert_called_once_with(
        name="file.txt",
        content="dGVzdCBjb250ZW50"
    )

    # Verify attachment added to email
    assert mock_send_email.attachment == [mock_attachment]

    # Verify API call executed
    mailer.api_instance.send_transac_email.assert_called_once_with(mock_send_email)
