# Generated by ChatGPT

import os
import pytest
import mongomock
from flask import Flask, g

# Import the module under test
from flaskr.services.util import db

@pytest.fixture
def app(monkeypatch):
    """Create and configure a new Flask app for testing."""
    app = Flask(__name__)
    app.config["MONGODB_URI"] = "mongodb://fake-uri"
    app.config["MONGODB_DB"] = "TestDB"

    # Patch MongoClient to use mongomock
    monkeypatch.setattr(db, "MongoClient", lambda uri, **kwargs: mongomock.MongoClient())

    db.init_app(app)
    return app

def test_get_mongo_client_creates_and_caches_client(app):
    with app.app_context():
        client1 = db.get_mongo_client()
        assert client1 is not None
        assert "mongo_client" in g

        # Should return the cached client
        client2 = db.get_mongo_client()
        assert client1 is client2

def test_get_mongo_client_creates_and_caches_client(app):
    with app.app_context():
        client1 = db.get_mongo_client()
        assert client1 is not None
        assert "mongo_client" in g

        # Should return the cached client
        client2 = db.get_mongo_client()
        assert client1 is client2

def test_get_db_returns_default_database(app):
    with app.app_context():
        client = db.get_mongo_client()
        db_instance = db.get_db()
        # Database should be the same as returned by the client
        assert db_instance.name == "TestDB"
        assert db_instance == client["TestDB"]

def test_get_db_with_custom_name(app):
    with app.app_context():
        client = db.get_mongo_client()
        db_instance = db.get_db("CustomDB")
        assert db_instance.name == "CustomDB"
        assert db_instance == client["CustomDB"]

def test_close_mongo_client_closes_and_removes_from_g(app):
    with app.app_context():
        client = db.get_mongo_client()
        assert "mongo_client" in g
        db.close_mongo_client()
        assert "mongo_client" not in g

def test_close_mongo_client_does_nothing_if_not_set(app):
    with app.app_context():
        assert "mongo_client" not in g
        # Should not raise
        db.close_mongo_client()
        assert "mongo_client" not in g
