# Generated by ChatGPT

import pytest
import mongomock
from flaskr.services.mongodb.AWS_creds_DBsrv import AwsCredsDBService

@pytest.fixture
def mock_db():
    """Fixture for an in-memory MongoDB using mongomock."""
    client = mongomock.MongoClient()
    return client["test_db"]

@pytest.fixture
def service(mock_db):
    """Fixture for AwsCredsDBService with mock DB provider."""
    def db_provider():
        return mock_db
    return AwsCredsDBService(db_provider)

def test_create_document_inserts_data(service, mock_db):
    data = {"access_key": "ABC123", "secret_key": "XYZ789"}
    inserted_id = service.create_document(data)
    assert inserted_id is not None

    saved_doc = mock_db["AWSCreds"].find_one({"access_key": "ABC123"})
    assert saved_doc is not None
    assert saved_doc["access_key"] == "ABC123"

def test_create_duplicate_fails(service, mock_db):
    # First insert should succeed
    data = {"access_key": "DUPLICATE", "secret_key": "SECRET"}
    service.create_document(data)

    # Second insert with the same data should raise ValueError
    with pytest.raises(ValueError):
        service.create_document(data)

    # Ensure only one document exists in the collection
    count = mock_db["AWSCreds"].count_documents({"access_key": "DUPLICATE"})
    assert count == 1

def test_get_document_by_id_returns_doc(service, mock_db):
    inserted = mock_db["AWSCreds"].insert_one({"access_key": "KEY"}).inserted_id
    doc = service.get_document_by_id(str(inserted))
    assert doc["_id"] == str(inserted)
    assert doc["access_key"] == "KEY"

def test_get_all_documents_returns_list(service, mock_db):
    mock_db["AWSCreds"].insert_many([
        {"access_key": "A"},
        {"access_key": "B"}
    ])
    docs = service.get_all_documents()
    assert len(docs) == 2
    assert {d["access_key"] for d in docs} == {"A", "B"}

def test_update_document_modifies_data(service, mock_db):
    inserted = mock_db["AWSCreds"].insert_one({"access_key": "OLD"}).inserted_id
    modified_count = service.update_document(str(inserted), {"access_key": "NEW"})
    assert modified_count == 1

    updated = mock_db["AWSCreds"].find_one({"_id": inserted})
    assert updated["access_key"] == "NEW"

def test_delete_document_removes_doc(service, mock_db):
    inserted = mock_db["AWSCreds"].insert_one({"access_key": "DELETE"}).inserted_id
    deleted_count = service.delete_document(str(inserted))
    assert deleted_count == 1

    doc = mock_db["AWSCreds"].find_one({"_id": inserted})
    assert doc is None

def test_delete_all_documents_clears_collection(service, mock_db):
    mock_db["AWSCreds"].insert_many([{"a": 1}, {"a": 2}])
    deleted_count = service.delete_all_documents()
    assert deleted_count == 2
    assert mock_db["AWSCreds"].count_documents({}) == 0

def test_get_collection_stats_returns_expected_fields(service, mock_db):
    mock_db["AWSCreds"].insert_many([
        {"type": "alpha"}, {"type": "beta"}, {"type": "alpha"}
    ])
    stats = service.get_collection_stats()
    assert stats["collection_name"] == "AWSCreds"
    assert stats["total_documents"] == 3
    assert "alpha" in stats["type_breakdown"]

def test_query_documents_filters_correctly(service, mock_db):
    mock_db["AWSCreds"].insert_many([
        {"status": "active"}, {"status": "inactive"}
    ])
    active_docs = service.query_documents({"status": "active"})
    assert len(active_docs) == 1
    assert active_docs[0]["status"] == "active"
