# Generated by ChatGPT

import pytest
import uuid
from backend.flaskr.services.mongodb.role_attempts_DBsrv import RoleAttemptsDBService

@pytest.fixture
def mock_db():
    import mongomock
    client = mongomock.MongoClient()
    return client["test_db"]

@pytest.fixture
def service(mock_db):
    def db_provider():
        return mock_db
    return RoleAttemptsDBService(db_provider)

def test_get_attempts_by_session_returns_matching_documents(service, mock_db):
    session_id = str(uuid.uuid4())
    mock_db["AssumeRoleAttempts"].insert_many([
        {"session_id": session_id, "status": "success"},
        {"session_id": "another-session", "status": "failed"}
    ])

    results = service.get_attempts_by_session(session_id)
    assert len(results) == 1
    assert results[0]["session_id"] == session_id
    assert results[0]["status"] == "success"

def test_get_attempts_by_session_returns_empty_if_none(service, mock_db):
    results = service.get_attempts_by_session(str(uuid.uuid4()))
    assert results == []

def test_get_attempts_by_starting_identity_returns_matching_documents(service, mock_db):
    mock_db["AssumeRoleAttempts"].insert_many([
        {"starting_identity": "Alice", "status": "success"},
        {"starting_identity": "Bob", "status": "failed"}
    ])

    results = service.get_attempts_by_starting_identity("Alice")
    assert len(results) == 1
    assert results[0]["starting_identity"] == "Alice"
    assert results[0]["status"] == "success"

def test_get_attempts_by_starting_identity_empty_if_none(service, mock_db):
    results = service.get_attempts_by_starting_identity("NonExistent")
    assert results == []

def test_query_inherits_base_methods(service, mock_db):
    # Ensures BaseMongoDBService.query_documents works through subclass
    mock_db["AssumeRoleAttempts"].insert_one({"starting_identity": "Charlie"})
    results = service.query_documents({"starting_identity": "Charlie"})
    assert len(results) == 1
    assert results[0]["starting_identity"] == "Charlie"
