# Generated by ChatGPT

import pytest
import mongomock
from flaskr.services.mongodb.report_DBsrv import ReportDBService

@pytest.fixture
def mock_db():
    """In-memory MongoDB using mongomock."""
    client = mongomock.MongoClient()
    return client["test_db"]

@pytest.fixture
def service(mock_db):
    """ReportDBService with a mock DB provider."""
    def db_provider():
        return mock_db
    return ReportDBService(db_provider)

def test_create_document_inserts_data(service, mock_db):
    data = {"report_name": "Monthly"}
    inserted_id = service.create_document(data)
    assert inserted_id is not None

    saved_doc = mock_db["Reports"].find_one({"report_name": "Monthly"})
    assert saved_doc is not None
    assert saved_doc["report_name"] == "Monthly"

def test_get_document_by_id_returns_doc(service, mock_db):
    inserted = mock_db["Reports"].insert_one({"report_name": "Weekly"}).inserted_id
    doc = service.get_document_by_id(str(inserted))
    assert doc["_id"] == str(inserted)
    assert doc["report_name"] == "Weekly"

def test_get_all_documents_returns_list(service, mock_db):
    mock_db["Reports"].insert_many([{"name": "R1"}, {"name": "R2"}])
    docs = service.get_all_documents()
    assert len(docs) == 2
    assert {d["name"] for d in docs} == {"R1", "R2"}

def test_update_document_modifies_data(service, mock_db):
    inserted = mock_db["Reports"].insert_one({"name": "Old"}).inserted_id
    modified_count = service.update_document(str(inserted), {"name": "New"})
    assert modified_count == 1

    updated = mock_db["Reports"].find_one({"_id": inserted})
    assert updated["name"] == "New"

def test_delete_document_removes_doc(service, mock_db):
    inserted = mock_db["Reports"].insert_one({"name": "DeleteMe"}).inserted_id
    deleted_count = service.delete_document(str(inserted))
    assert deleted_count == 1

    doc = mock_db["Reports"].find_one({"_id": inserted})
    assert doc is None

def test_delete_all_documents_clears_collection(service, mock_db):
    mock_db["Reports"].insert_many([{"a": 1}, {"a": 2}])
    deleted_count = service.delete_all_documents()
    assert deleted_count == 2
    assert mock_db["Reports"].count_documents({}) == 0

def test_get_collection_stats_returns_expected_fields(service, mock_db):
    mock_db["Reports"].insert_many([
        {"type": "finance"}, {"type": "hr"}, {"type": "finance"}
    ])
    stats = service.get_collection_stats()
    assert stats["collection_name"] == "Reports"
    assert stats["total_documents"] == 3
    assert stats["type_breakdown"]["finance"] == 2
    assert stats["type_breakdown"]["hr"] == 1

def test_query_documents_filters_correctly(service, mock_db):
    mock_db["Reports"].insert_many([
        {"status": "active"}, {"status": "inactive"}
    ])
    results = service.query_documents({"status": "active"})
    assert len(results) == 1
    assert results[0]["status"] == "active"
